added a new bot detection agent
gautam2002/forta-bots-challenges pull request #1
Opened 2022-10-04 09:04 UTC by gautam2002

## WHAT?
A bot that detects if a new agent is created from a specific address. Bot one of the intern bot challenges

2022-10-04 11:50 UTC, 0xtaf requested changes
Great bot! congrats! no logic related comments but only some best practices about our system. 

besides these comments, commit messages should should follow [this guideline](https://www.notion.so/nethermind/Definition-of-Done-Guidelines-6d81308092214ec6a0d13089127c87f9#6a7c580d8266480290921bacf138a7c5) and they should be small and feature related. putting everything into single commit would create problems.

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/src/agent.ts
> +      const { owner, metadata, agentId, chainIds } = newAgentDescription.args;
```suggestion
    listAllRegisterTxEvent.forEach((newBotDescription) => {
      const { owner, metadata, agentId, chainIds } = newBotDescription.args;
```
just wording.

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/src/agent.ts
> +          description: "Detects every new Bot deployed from Nethermind Address",
this should be the description of this particular alert. so it should be something like "A new bot has been deployed from Nethermind"

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/src/agent.ts
> +          metadata: {
```suggestion
          type: FindingType.Info,
          protocol: "Nethermind"
          metadata: {
```
protocol field is also what we use in a finding object and it's generally name of the client. here we can put "Nethermind"

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/src/agent.spec.ts
> +  describe("handleTransaction", () => {
nesting describes should be avoided.

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/src/agent.spec.ts
> +    it("must return the exact data", async () => {
test names should describe what the test actually does. for example `it("returns findings if there are bots created from Nethermind address")` 

.addTraces

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/src/agent.spec.ts
> +      mockTxEvent.filterFunction = jest.fn().mockReturnValue([mockBotTxEvent]);
instead of mocking `filterFunction`, we prefer actually simulating the function and catching it. see `addTraces` from `forta-agent-tools` to see how to simulate a function.

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/src/agent.spec.ts
> +        Finding.fromObject({
this finding object could be wrapped inside a `createFinding` function outside of this test case. we may need to use it in multiple scenarios.

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/src/agent.spec.ts
> +    it("Return empty array if from and to address are changed", async () => {
this doesn't describe what this test actually does. what I understand is that it should still emit `createAgent` function but shouldn't return a finding because the `from` is not Nethermind

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/README.md
> +# New Bot Deployment Detection Agent
```suggestion
# New Bot Deployment Detection Bot
```

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/README.md
> +This agent detects if a new bot is deployed from a specific address. It achieves this by filtering the transactions that match the createAgent function signature.
```suggestion
This bot detects if a new bot is deployed from a specific address. It achieves this by filtering the transactions that match the createAgent function signature.
```

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/README.md
> +Describe each of the types of alerts fired by this agent
```suggestion

```

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/README.md
> +  - Metadata: `owner`(owner address), `Ipfsmetadata`(Bot metadata content hash ID IPFS), `agentID`(uint256), `chainIds`
```suggestion
  - Metadata: 
          - `owner`: Owner address, 
          - `Ipfsmetadata`: Bot metadata content hash ID IPFS, 
          - `agentID`: Id of the deployed bot, 
          - `chainIds`: List of supported chains
```

2022-10-04 11:50 UTC, 0xtaf commented on detection-bot/README.md
> +}
this block is not necessary because there could be many test cases.

2022-10-06 09:22 UTC, Vxatz requested changes
Hey @gautam2002, most of my comments are of minor importance

Two things you can also change:

1) Change the bot's root folder name to be more descriptive 
2) You can add a test in which multiple findings are returned for multiple bots deployed in the same tx

2022-10-06 09:22 UTC, Vxatz commented on detection-bot/README.md
> +This bot detects if a new bot is deployed from a specific address. It achieves this by filtering the transactions that match the createAgent function signature.
```suggestion
This bot detects if a new bot is deployed from a specific address. It achieves this by filtering the transactions that match the `createAgent` function signature.
```

2022-10-06 09:22 UTC, Vxatz commented on detection-bot/README.md
> +The agent behavior can be verified with the following transactions:
```suggestion
The bot behavior can be verified with the following transactions:
```

2022-10-06 09:22 UTC, Vxatz commented on detection-bot/src/shared.ts
> +  // Agent activity on Polygon: https://polygonscan.com/address/0x61447385B019187daa48e91c55c02AF1F1f3F863
```suggestion
  // Bot activity on Polygon: https://polygonscan.com/address/0x61447385B019187daa48e91c55c02AF1F1f3F863
```

2022-10-06 09:22 UTC, Vxatz commented on detection-bot/src/agent.ts
> + * @param sharedConstant : Constants like createAgents function signature and to(polygon) and from(Nethermind) address.
```suggestion
 * @param sharedConstant : Constants like createAgent function signature and to(polygon) and from(Nethermind) address.
```

2022-10-06 09:22 UTC, Vxatz commented on detection-bot/README.md
> +    - `Ipfsmetadata`: Bot metadata hash ID stored in IPFS
```suggestion
    - `IpfsMetadata`: Bot metadata hash ID stored in IPFS
```

Using camelCase (should also be changed in the bot logic)

2022-10-06 09:22 UTC, Vxatz commented on detection-bot/src/agent.ts
> +          name: "Nethermind Bot Detection",
```suggestion
          name: "New Nethermind Bot Deployment Detection",
```

Suggesting a more descriptive name

2022-10-06 09:22 UTC, Vxatz commented on detection-bot/src/agent.spec.ts
> +    handleTransaction = provideHandleTransaction(sharedConstant);
The `sharedConstant` object must be mocked so that no real addresses are used (you can use `createAddress` from the General Agents Module to create fake addresses)

As you correctly pass it as an argument to the wrapper function, this will be a simple modification.

2022-10-06 09:22 UTC, Vxatz commented on detection-bot/src/agent.spec.ts
> +  it("Should return empty findings if nethermind address is changed", async () => {
Instead of switching the addresses you can also use `createAddress` here to create a non-Nethermind address

2022-10-07 10:52 UTC, Vxatz approved these changes
Clearly not a big deal right now, but for future developments it's good to follow our typical naming convention for the bot's folder name which in this case would be: `New-Deployment-Detection-Bot`

Approved ✅

2022-10-07 11:52 UTC, merged