@intern challenges/two
gautam2002/forta-bots-challenges pull request #2
Opened 2022-10-17 12:46 UTC by gautam2002

WHAT? 
Uniswap swap detection bot detects swaps made on uniswapv3 without keeping a reference of the pool address.

2022-10-20 07:32 UTC, Vxatz requested changes
Great job in computing the addresses 💪 

Only major comments regard mocking the provider and using the `blockTag`

As you mention in the description you can then add a couple more tests.

2022-10-20 07:32 UTC, Vxatz commented on Uniswap-Swap-Event-Detection-Bot/src/agent.ts
> +const dataCache: LRU<string, string[]> = new LRU<string, string[]>({ max: 500 });
```suggestion
const dataCache: LRU<string, string[]> = new LRU<string, string[]>({ max: 10_000 });
```
(Typically we use this size)

2022-10-22 06:57 UTC, 0xtaf requested changes
great work! 👏 
I have only very small requests.

2022-10-22 06:57 UTC, 0xtaf commented on Uniswap-Swap-Event-Detection-Bot/src/agent.ts
> +}
this block is better to be inside in a separate file like `utils.ts`. we try to keep agent.ts as simple as possible by not adding utility functions into it.
also, if you use it here, you need to remove `export` keyword because it's not imported anywhere.

2022-10-22 06:57 UTC, 0xtaf commented on Uniswap-Swap-Event-Detection-Bot/src/agent.ts
> +      const thisBlockNumber = txEvent.blockNumber;
this should be moved above the loop because it will only have one block number for this txEvent. so it shouldn't be assigned in each loop.

2022-10-22 06:57 UTC, 0xtaf commented on Uniswap-Swap-Event-Detection-Bot/package.json
> +    "test": "jest"
```suggestion
    "test": "jest --detectOpenHandles"
```
added this because jest returns a warning about it

2022-10-22 14:24 UTC, 0xtaf approved these changes

2022-10-22 16:34 UTC, Vxatz approved these changes

2022-10-23 04:48 UTC, merged